apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open5g-app
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/tanisha1901/open5gcore
    chart: helm-chart
    path: helm-chart
    targetRevision: 0.0.1
  destination:
    namespace: open5g-application
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true

